-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 09:28:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema esispace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esispace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esispace` DEFAULT CHARACTER SET latin1 ;
USE `esispace` ;

-- -----------------------------------------------------
-- Table `esispace`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`admin` (
  `nom` VARCHAR(30) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `photo_prf` VARCHAR(50) NOT NULL,
  `motpass` VARCHAR(45) NULL,
  `idadmin` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `esispace`.`enseignent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`enseignent` (
  `numdensg` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(30) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `date_ns` DATE NOT NULL,
  `grade` VARCHAR(30) NOT NULL,
  `motpass` VARCHAR(50) NOT NULL,
  `photo_prf` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`numdensg`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `esispace`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`etudiant` (
  `numdinsc` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(30) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `date_ns` DATE NOT NULL,
  `lieu_ns` VARCHAR(20) NOT NULL,
  `groupe` VARCHAR(20) NOT NULL,
  `annee` VARCHAR(20) NOT NULL,
  `motpass` VARCHAR(50) NOT NULL,
  `photo_prf` VARCHAR(50) NULL DEFAULT NULL,
  `section` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`numdinsc`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `esispace`.`Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`Module` (
  `idModule` INT NOT NULL,
  `Nommodule` VARCHAR(45) NULL,
  `coff` VARCHAR(45) NULL,
  `annee` VARCHAR(45) NULL,
  `semestre` VARCHAR(45) NULL,
  PRIMARY KEY (`idModule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`message` (
  `idmessage` INT NOT NULL,
  `text` TEXT NULL,
  `id_envoyer` VARCHAR(60) NULL,
  `id_recevoir` VARCHAR(60) NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_message_etudiant1_idx` (`id_envoyer` ASC) VISIBLE,
  INDEX `fk_message_etudiant2_idx` (`id_recevoir` ASC) VISIBLE,
  CONSTRAINT `fk_message_etudiant1`
    FOREIGN KEY (`id_envoyer`)
    REFERENCES `esispace`.`etudiant` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_etudiant2`
    FOREIGN KEY (`id_recevoir`)
    REFERENCES `esispace`.`etudiant` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_enseignent1`
    FOREIGN KEY (`id_envoyer`)
    REFERENCES `esispace`.`enseignent` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_enseignent2`
    FOREIGN KEY (`id_recevoir`)
    REFERENCES `esispace`.`enseignent` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_admin1`
    FOREIGN KEY (`id_envoyer`)
    REFERENCES `esispace`.`admin` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_admin2`
    FOREIGN KEY (`id_recevoir`)
    REFERENCES `esispace`.`admin` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`note` (
  `idnote` INT NOT NULL,
  `cntrl_intr` VARCHAR(45) NULL,
  `cntrl_final` VARCHAR(45) NULL,
  `td` VARCHAR(45) NULL,
  `etudiant_numdinsc` VARCHAR(20) NOT NULL,
  `Module_idModule` INT NOT NULL,
  PRIMARY KEY (`idnote`),
  INDEX `fk_note_etudiant1_idx` (`etudiant_numdinsc` ASC) VISIBLE,
  INDEX `fk_note_Module1_idx` (`Module_idModule` ASC) VISIBLE,
  CONSTRAINT `fk_note_etudiant1`
    FOREIGN KEY (`etudiant_numdinsc`)
    REFERENCES `esispace`.`etudiant` (`numdinsc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_Module1`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `esispace`.`Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`releveNote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`releveNote` (
  `idreleve` INT NOT NULL,
  `annee` VARCHAR(45) NULL,
  `semestre` VARCHAR(45) NULL,
  `moyenne` VARCHAR(45) NULL,
  `etudiant_numdinsc` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idreleve`),
  INDEX `fk_releveNote_etudiant1_idx` (`etudiant_numdinsc` ASC) VISIBLE,
  CONSTRAINT `fk_releveNote_etudiant1`
    FOREIGN KEY (`etudiant_numdinsc`)
    REFERENCES `esispace`.`etudiant` (`numdinsc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`seance` (
  `idseance` INT NOT NULL,
  `type` ENUM("cours", "td", "tp") NULL,
  `duree` VARCHAR(45) NULL,
  `jour` VARCHAR(45) NULL,
  `grp_sec` VARCHAR(45) NULL,
  `sall_amphi` VARCHAR(45) NULL,
  `enseignent_numdensg` VARCHAR(20) NOT NULL,
  `Module_idModule` INT NOT NULL,
  `plage_hr` VARCHAR(45) NULL,
  PRIMARY KEY (`idseance`),
  INDEX `fk_seance_enseignent1_idx` (`enseignent_numdensg` ASC) VISIBLE,
  INDEX `fk_seance_Module1_idx` (`Module_idModule` ASC) VISIBLE,
  CONSTRAINT `fk_seance_enseignent1`
    FOREIGN KEY (`enseignent_numdensg`)
    REFERENCES `esispace`.`enseignent` (`numdensg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seance_Module1`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `esispace`.`Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`spicialité`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`spicialité` (
  `spicialité` INT NOT NULL,
  `nom_spic` VARCHAR(45) NULL,
  `etudiant_numdinsc` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`spicialité`),
  INDEX `fk_table1_etudiant1_idx` (`etudiant_numdinsc` ASC) VISIBLE,
  CONSTRAINT `fk_table1_etudiant1`
    FOREIGN KEY (`etudiant_numdinsc`)
    REFERENCES `esispace`.`etudiant` (`numdinsc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`annee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`annee` (
  `idannee` INT NOT NULL,
  `nom_annee` VARCHAR(45) NULL,
  PRIMARY KEY (`idannee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`section` (
  `idsection` INT NOT NULL,
  `nom_section` VARCHAR(45) NULL,
  `annee_idannee` INT NOT NULL,
  PRIMARY KEY (`idsection`),
  INDEX `fk_section_annee1_idx` (`annee_idannee` ASC) VISIBLE,
  CONSTRAINT `fk_section_annee1`
    FOREIGN KEY (`annee_idannee`)
    REFERENCES `esispace`.`annee` (`idannee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esispace`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esispace`.`groupe` (
  `idgroupe` INT NOT NULL,
  `num_groupe` VARCHAR(45) NULL,
  `section_idsection` INT NOT NULL,
  PRIMARY KEY (`idgroupe`),
  INDEX `fk_groupe_section1_idx` (`section_idsection` ASC) VISIBLE,
  CONSTRAINT `fk_groupe_section1`
    FOREIGN KEY (`section_idsection`)
    REFERENCES `esispace`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
